parameters:
    format_champ_integer2: /^[0-9]*$/
    
services:

    integration.antispam:
        class: Blog\IntegrationBundle\Antispam\Antispam
        arguments: ['@logger']
        tags:
            -  { name: twig.extension }
